config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  #get 'home/index'
  get 'home/team'
  post 'home/team' => 'home/team'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :common, :only => [:index,:team]

  def common
    @hero_name = Faker::Superhero.name #able to access this instance variable through the methods
    @power =  Faker::Superhero.power #in the before_action
    @food = Faker::Food.dish 
    @job = Faker::Job.title
    @job_power = Faker::Company.bs
    @job_power = @job_power.titleize 
    @random_number = rand(1..1000)
    @set_num = rand(1..3)
    @background = rand(1..2)

    if @set_num == 1
    	@set = "set1"
    elsif @set_num == 2
    	@set = "set2"
    else 
      @set = "set3"
    
    end

    
    if @background == 1
    	@bg = "bg1"
    else
    	@bg = "bg2"
    
    end




    @avatar = Faker::Avatar.image(slug: @random_number , size: "300x300", format: "bmp", set: @set, bgset: @bg)

  end
  
  def index
  end

  def team
    @team_number = params[:team_number].to_i
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_create_team.html.erb
 <div class="row">
  <br/> 
  <div class="col-md-4">
  	<%= form_tag home_team_path, :method => 'POST' do %>
  	<%= select_tag( :team_number, options_for_select([
            ['1', 1],
            ['2', 2],
            ['3', 3],  
            ['4', 4],
            ['5', 5],
            ['6', 6],
            ['7', 7],
            ['8', 8],
            ['9', 9],
            ['10', 10],
            ]), class: 'form-control') %>
 

     <br/><br/>
    <%= submit_tag "Build Your Team!", class: "btn-btn-primary" %>
  	<%  end %>
  </div>
  <div class="col-md-4">
 </div>


 <div class="col-md-4">
 </div>

  
  </div>


 </div>
</div>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'SUPERHERO NAME GENERATOR', root_path, class:'navbar-brand' %>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">        
       </ul>
        <ul class="nav navbar-nav navbar-right">
         <li><%= link_to 'Home Page', root_path %></li> 
          <li><%= link_to 'Create A Team', home_team_path %></li>
        
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/_show.html.erb
<% @team_number.times do %>

<div class="row">
  		<br/> 
  		<div class="col-md-4">
  	
    <% random_number = rand(1..1000) %>
    <% set_num = rand(1..3) %>
    <% background = rand(1..2) %>

      <% if set_num == 1 %>
        <% set = "set1" %>
    <% elsif set_num == 2 %>
       <% set = "set2" %>
    <% else set_num == 3 %>
       <% set = "set3" %>
    
    <% end %>

    
    <% if background == 1 %>
     <%  bg = "bg1" %>
    <% else %>
      <% bg = "bg2" %>
    
    <% end %>




    <% avatar = Faker::Avatar.image(slug: random_number , size: "300x300", format: "bmp", set: set, bgset: bg) %>

 

        <img src="<%= avatar %>">
  		</div>
        
    <div class="col-md-4">
      <h3>
    Super Hero Name:<br/>
    <span class="red"><%= Faker::Superhero.name %></span><br/><br/><br/>
    </h3>

    <h3>
    Power:<br/> 
    <span class="red"><%= Faker::Superhero.power %></span>  <br/><br/> 
    </h3>

    <h3>
    Favourite Food:<br/>
    <span class="red"><%=  Faker::Food.dish  %></span><br/><br/> 
    </h3>

    <h4> 
    Your Undercover Day Job is:<br/> <%=  Faker::Job.title %><br/><br/>  
    Your Corporate Superpower is:<br/> <%=  Faker::Company.bs.titleize  %><br/><br/>
   </h4>
   </div>

   
   <div class="col-md-4">
  </div>
   
   <div class="row">
    <div class="col-md-12">
      <hr>
  </div>
  
  </div>
     
</div>

<% end %>
<div class="panel-footer"><%= link_to 'Create Your Superhero', root_path %>
  </div>

app/views/home/index.html.erb
<br/> 
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title dark"><%= link_to 'Click Here To Create New A Superhero', root_path %></h3>
  </div>
  <div class="panel-body">
  	<div class="row">
  		<br/> 
  		<div class="col-md-4">
  			<img src="<%= @avatar %>">
  		</div>
        <div class="col-md-4">
    
    <h3>
    Super Hero Name:<br/>
    <span class="red"><%= @hero_name %></span><br/><br/><br/>
    </h3>

    <h3>
    Power:<br/> 
    <span class="red"><%= @power %></span>  <br/><br/> 
    </h3>

    <h3>
    Favourite Food:<br/>
    <span class="red"><%=  @food %></span><br/><br/> 
    </h3>

    <h4> 
    Your Undercover Day Job is:<br/> <%=  @job %><br/><br/>  
    Your Corporate Superpower is:<br/> <%=  @job_power %><br/><br/>
   </h4>
   </div>
   </div>
   </div>
  
  <div class="panel-footer"><%= link_to 'Create A Whole Superhero Team', home_team_path %>
  </div>
</div>

app/views/home/team.html.erb
<br/>



<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title dark"><% if @team_number > 0 %>Your Superhero Team... <% else %>How Many Team Members Do You Want ? <% end %></h3>
  </div>
  <div class="panel-body">
 
 <% if @team_number > 0 %>
   <%= render 'home/show'  %>.
<% else %>
  <%= render 'home/create_team'  %>
<% end %>

  


  



</div>
</div>

  
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Superhero Name Generator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!--To make the app responsive on mobile-->
  </head>

  <body>
  <%= render 'home/navbar' %>
   <div class="container">
    <%= yield %>
  </div>
  <br/> <br/>
   <br/> <br/>
   <center>
    <p>Copyright &copy; 2020 LM - All rights reserved</p>
   </center>
  </body>
</html>